### ISSUE TITLE
Добавьте в Makefile $(DESTDIR) перед абсолютными путями

### ISSUE THREAD

**Issue by antohami** [alsoijw/populate#1]
Переменная $(DESTDIR) в Makefile нужна для установки в сборочницу, а не в реальную систему, на этапе сборки rpm-пакета.

**Comment by alsoijw** [comment]
Это нужно только в правиле install или везде?

**Comment by antohami** [comment]
Ну, чтобы собрать rpm, только в правиле install. Но ничего страшного, если и в uninstall будет.
Использование переменной $(DESTDIR) в Makefile позволяет устанавливать в любое нужное вам место программу, ну и соответственно и удалять. Выглядит это так
make install DESTDIR=/patch/to/directory
и соответственно, чтобы удалить:
make uninstall DESTDIR=/patch/to/directory

**Comment by alsoijw** [comment]
Я правильно понимаю что в команде путь должен быть абсолютным? Без её выполнения невозможно использовать программу, так как файл org.alsoijw.populate.gschema.xml тоже должен быть установлен в "/usr/share/glib-2.0/schemas/", но можно собрать пакет. В случае если собирается пакет, то эта команда бесполезна.

```
glib-compile-schemas /usr/share/glib-2.0/schemas/
```

**Comment by alsoijw** [comment]
Сделано. 87fbb0045033b24bbd53ec36e69d150206bcd1af Для использования приложения в случае обновления org.alsoijw.populate.gschema.xml обязательно обновление glib-compile-schemas

**Comment by antohami** [comment]
Перед /usr/share/glib-2.0/schemas/ тоже должен быть $(DESTDIR) указан. Иначе установка в сборочнице будет заканчиваться ошибкой. А так да, в сборочнице эта команда бесполезна. Её нужно использовать в послеустановочном скрипте. Но похоже в Альт Линукс это всё само делается (посмотрел несколько спеков).
В-общем, добавляйте. Ничего не поломается, зато в сборочнице будет нормально собираться.

**Comment by alsoijw** [comment]
А кто разбивает на пред установочный, постустановочные скрипты?

**Comment by antohami** [comment]
Майнтейнер. Допустим в rpm-based дистрибутивах в спек-файлах есть секция %postinstall. Её содержимое пакуется в послеустановочный скрипт. Вам как разработчику нужно только Makefile правильный сделать, чтобы майнтейнер мог использовать стандартный макрос %makeinstall_std.
