### ISSUE TITLE
Сделайте относительными пути в исходном коде

### ISSUE THREAD

**Issue by antohami** [alsoijw/populate#2]
Уберите в исходном коде абсолютные пути, это позволит запускать программу, не устанавливая в систему. Для этого нужно лишь удалить слэш вначале путей. Например был /usr/bin/populate станет usr/bin/populate

**Comment by alsoijw** [comment]
Я правильно понимаю что строка будет примерно такого вида $(DESTDIR)usr/bin/populate

**Comment by antohami** [comment]
Нет. Переменная $(DESTDIR) передаётся Makefile на этапе установки и в исходном коде её не нужно указывать. Нам же для того, чтобы сделать адрессацию относительной, нужно всего лишь убрать первый слэш у всех путей в исходном коде. Это позволит запускать программу из любого места, главное, чтобы структура каталогов не была нарушена.

**Comment by antohami** [comment]
Прошу прощения, ерунду написал. В исходном коде только путь к локали используется, а сделать его относительным большая проблема. Так как путь относителен того места откуда происходит запуск, а не того, где лежит бинарик, то вариант с относительным путём явно не подходит.
